// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"
)

type DisallowToken struct {
	TokenID   string
	CreatedAt time.Time
}

type OpenidNonce struct {
	ID          int64
	Endpoint    string
	NonceTime   time.Time
	NonceString string
	CreatedAt   time.Time
}

type Session struct {
	ID        int64
	UserID    string
	TokenID   string
	CreatedAt time.Time
}

type User struct {
	ID        string
	Alias     string
	AvatarUrl string
	CreatedAt time.Time
}

type UserRole struct {
	UserID string
	Role   string
}
