// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: openid_nonce.sql

package queries

import (
	"context"
	"time"
)

const insertNonce = `-- name: InsertNonce :exec
insert into openid_nonce (endpoint, nonce_time, nonce_string) 
  values (?, ?, ?)
`

type InsertNonceParams struct {
	Endpoint    string
	NonceTime   time.Time
	NonceString string
}

func (q *Queries) InsertNonce(ctx context.Context, arg InsertNonceParams) error {
	_, err := q.db.ExecContext(ctx, insertNonce, arg.Endpoint, arg.NonceTime, arg.NonceString)
	return err
}
