// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package queries

import (
	"context"
)

const insertSession = `-- name: InsertSession :one
insert into session (user_id, token_id)
  values (?, ?)
  returning id, user_id, token_id, created_at
`

type InsertSessionParams struct {
	UserID  string
	TokenID string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, insertSession, arg.UserID, arg.TokenID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.CreatedAt,
	)
	return i, err
}
