// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package queries

import (
	"context"
)

const selectUser = `-- name: SelectUser :one
select id, alias, avatar_url, created_at from user
where user.id = ?
`

func (q *Queries) SelectUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
insert into user (id, alias, avatar_url)
  values (?, ?, ?)
  on conflict do update
  set alias = excluded.alias,
  avatar_url = excluded.avatar_url
  returning id, alias, avatar_url, created_at
`

type UpsertUserParams struct {
	ID        string
	Alias     string
	AvatarUrl string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, arg.ID, arg.Alias, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}
