// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_role.sql

package queries

import (
	"context"
)

const initRole = `-- name: InitRole :exec
insert or ignore into user_role (user_id)
  values (?)
`

func (q *Queries) InitRole(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, initRole, userID)
	return err
}

const selectRole = `-- name: SelectRole :one
select user_id, role from user_role
where user_id = ?
`

func (q *Queries) SelectRole(ctx context.Context, userID string) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, selectRole, userID)
	var i UserRole
	err := row.Scan(&i.UserID, &i.Role)
	return i, err
}
